spring:
  application:
    name: service-consumer
server:
  port: 9102
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
